spring.application.name=library
spring.datasource.username=ragnar
spring.datasource.password=ragnar
spring.datasource.url=jdbc:mysql://localhost/library
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.main.banner-mode=off